### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by ghost** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#1]
When trying to login I am getting this error:
login failed exception 'GuzzleHttp\Exception\RequestException' with message '[curl](#7) See http://curl.haxx.se/libcurl/c/libcurl-errors.html for an explanation of cURL errors [url] https://accounts.ea.com/connect/auth?response_type=code&client_id=EASFC-web&state=d6WpgMx2jio09LNU9bAU7Du_YtAkG93ShejiDZN_Je8&redirect_uri=http%3A%2F%2Fwww.easports.com%2Ffifa%2Flogin_check&locale=us&scope=basic.identity%20basic.persona%20signin%20offline' in

**Comment by ebess** [comment]
Yap, that's failure of the ea servers. I can't do anything about that. You need to catch the exception and retry.

**Comment by ghost** [comment]
I don't think it is? Maybe try for yourself? That url is getting breezed past on the web app?

**Comment by ebess** [comment]
I did, sometimes you get these exceptios with this login url and also with the secret answer (phishing) & shards url. Also, it might be that your credentials are wrong. Maybe I should catch them myself and delegate them with more specific exception messages.

Do you always get this exception or just sometimes?

**Comment by ghost** [comment]
I always got this exception on that exact URL which is why I reported it as I thought it was strange. Credentials are definitely correct.

**Comment by ebess** [comment]
Hey mate,
I think i can't help right here, there has to be something env-specific which will make your application crash. As intended the hashes in the url have to be always different and not the same. Did you added the guzzle cache plugin or something?

**Comment by ghost** [comment]
It not literally the same URL. It still has the same base URL but different variable values in the URL.

**Comment by ebess** [comment]
Hey mate,
was woundering whether you solved the problem? Sorry i couldnt help you

**Comment by ghost** [comment]
Hi, I think its a server error mate! Sorry for blaming your code :D
