### ISSUE TITLE
Buy it now function

### ISSUE THREAD

**Issue by mikebyte00** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#11]
Hey guys,

Wondering if anyone could help me with the parameter to 'Buy it Now' - 

I can bid on players fine, but if I wanted to straight away buy it now, what parameter do I need to send?

I have for bidding:
`*forge*->setBody(['bid' => $price], true)`

I've tried `['Buy it now'] => true]. true)` and `[Buy it now'] => $binPrice, true)`

Any  help on solving these parameters would be great.
many thanks.

**Comment by Unsworth94** [comment]
This is what I have:

``` php
$forge = Fut\Request\Forge::getForge($client, '/ut/game/fifa15/trade/' . $player['tradeId'] . '/bid', 'post', 'put');
$j = $forge->setNucId($export['nucleusId'])->setSid($export['sessionId'])->setPhishing($export['phishingToken'])->setBody(['bid' => (string)$BUY_PARAM['amount']], true)->getJson(); //buy the card

```

**Comment by mikebyte00** [comment]
Perfect, thanks Unsworth94.
