### ISSUE TITLE
Make a Bid

### ISSUE THREAD

**Issue by fasme** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#2]
Hi, good job,

Do you have an example of a BID?

I try with:

``` php
$client = new Client();
$cookieJar = new CookieJar();
$cookieSubscriber = new CookieSubscriber($cookieJar);
$client->getEmitter()->attach($cookieSubscriber);

$forge = Fut\Request\Forge::getForge($client, "/ut/game/fifa15/trade/".$tradeid."/bid", 'put');
        $json = $forge
->setNucId($export['nucleusId'])
    ->setSid($export['sessionId'])
    ->setPhishing($export['phishingToken'])
->getJson();
```

**Comment by ebess** [comment]
Hey, you need to put the override method to put and the real http method to post:

``` php
Fut\Request\Forge::getForge($client, "/ut/game/fifa15/trade/".$tradeid."/bid", 'post', 'put');
```
1. parameter is the real http method and the 4. one is the override method.

Also you need to append to payload of the request. In this case it is this stuff:

``` json
{"bid":<your_bid>}
```

So, its json, you need to set the body of the request as json - like this:

``` php
->setBody(['bid' => $price], true)
```

The second param of the setBody method will make the payload set as json string if set to true.

did it work out?

**Comment by fasme** [comment]
wow, now works, thanks
