### ISSUE TITLE
how can i pass origin verification ?

### ISSUE THREAD

**Issue by meezohd** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#4]
hi 
thanks for your work ... 

It always says "login failed".
I believe its because origin verification because whenever i update the page it sends an origin Verification code to my phone !

**Comment by meezohd** [comment]
its working now ! thanks :)

**Comment by meezohd** [comment]
unfortunately it works and then it doesn't !

is there anyway i can send a code to verify origin ?

**Comment by ebess** [comment]
Hey mate,
you are taking about the 'quick login' right? its pretty straight forward, you could extend the Fut\Connector\WebApp class and catch exception on each step and redo it.

if you are talking about the quick login, i did not implement it. does it help?

**Comment by meezohd** [comment]
thanks for replying ...

actually i was talking about origin verification, but i found out that i can just turn it off.

btw what is the "quick login" !? sounds like something i might be interested in :)
is it like multiple accounts login  ?

**Comment by ebess** [comment]
quick login is somethign the webapp do when you idle for some time, it will request new credentials the fast way. you have to reverse engineer the stuff. i have no spare time, didnt got to run the bot myself this season. :(
