### ISSUE TITLE
Sending to trade pile

### ISSUE THREAD

**Issue by CRCameron** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#6]
Sorry to bring this same issue up again but this is driving me crazy.

I'm trying to send items that I have won from my watchlist to tradepile using this code:

``` php
$wishlistForge = Fut\Request\Forge::getForge($client, '/ut/game/fifa15/watchlist', 'post', 'get');
$wishlistJson = $wishlistForge
    ->setNucId($export['nucleusId'])
    ->setSid($export['sessionId'])
    ->setPhishing($export['phishingToken'])
    ->getJson();

foreach ($wishlistJson['auctionInfo'] as $item) {
    $data_string = array(
        'itemData' => array(
            'tradeId' => $item['tradeId'],
            'id' => $item['itemData']['id'],
            'pile' => 'trade'
        )
    );

    $toTradeForge = Fut\Request\Forge::getForge($client, '/ut/game/fifa15/item', 'post', 'put');
    $toTradeJson = $toTradeForge
        ->setNucId($export['nucleusId'])
        ->setSid($export['sessionId'])
        ->setPhishing($export['phishingToken'])
        ->setBody($data_string, true)
        ->getJson();

}
```

The JSON always returns as Internal Server Error (ut) code 500.

Having looked at the other issue that was raised on this and looking at other APIs for FUT15 (and FUT14)  I really can't see what I'm doing wrong here. Any suggestions?

**Comment by meezohd** [comment]
$forge = \Fut\Request\Forge::getForge($client, '/ut/game/fifa15/item/'' , 'post','put');
    $json = $forge
    ->setNucId($export['nucleusId'])
    ->setSid($export['sessionId'])
    ->setPhishing($export['phishingToken'])
    ->setBody(array(
    'itemData' => [array(
        'pile' => 'trade',
        'id' => $id
      )]
    ), true)
    ->getJson();

**Comment by CRCameron** [comment]
Thanks for getting back to me so quick. This seems to have moved me on to another error code, 460. So now I have:

``` php
$wishlistForge = Fut\Request\Forge::getForge($client, '/ut/game/fifa15/watchlist', 'post', 'get');
$wishlistJson = $wishlistForge
    ->setNucId($export['nucleusId'])
    ->setSid($export['sessionId'])
    ->setPhishing($export['phishingToken'])
    ->getJson();

foreach ($wishlistJson['auctionInfo'] as $item) {

    $id = $item['itemData']['id'];

    $forge = \Fut\Request\Forge::getForge($client, '/ut/game/fifa15/item/'.$id.'' , 'post','put');
    $json = $forge
        ->setNucId($export['nucleusId'])
        ->setSid($export['sessionId'])
        ->setPhishing($export['phishingToken'])
        ->setBody(array(
            'itemData' => [array(
                'pile' => 'trade',
                'id' => $id
            )]
            ), true)
        ->getJson();

    print_r($json);
}
```

Which returns Array ( [debug] => [string] => Bad Request [reason] => [code] => 460 ).
Any further suggestions? would much appreciated. Thanks.

**Comment by ebess** [comment]
When you build the request, you can put the whole raw request data out to make it easy to debug. do it like this:

``` php
echo $forge->setNucId(...)->andSoOn()->getRequest();
```

So you can see the whole request headers etc. Now you might see the difference between your request and the web app request. Just adjust it accordingly.

Btw: there is no id in the url for moving the item to a certain pile.

**Comment by CRCameron** [comment]
Thanks guys, been a big help.

Turns out my problem was that I needed [ ] around the itemData array in  $data_string.

So now I have:

``` php
$data_string = array(
    'itemData' => [array(
        'tradeId' => $item['tradeId'],
        'id' => $item['itemData']['id'],
        'pile' => 'trade'
    )]
);
```

and it works. Thanks!
