### ISSUE TITLE
Send POST body

### ISSUE THREAD

**Issue by jhuriez** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#7]
Hi,

I want to send POST body for list auction.

The URI : $url = '/ut/game/fifa15/auctionhouse';
The post data : 

$body = 

```
(Array, 4 elements) ↵
     buyNowPrice (Integer): 1500
     duration (Integer): 3600
     itemData (Array, 1 element) ↵
                 id (Integer): 328949270
     startingBid (Integer): 1400
```

328949270 is the tradeId 
I get it when i do /ut/game/fifa15/tradepile
In auctionInfo[0][tradeId]

I do this for send the request : 

``` php
$forge = Fut\Request\Forge::getForge($this->client, '/ut/game/fifa15/auctionhouse', 'post', 'post');
$forge->setNucId($export['nucleusId'])
                    ->setSid($export['sessionId'])
                    ->setPhishing($export['phishingToken']);
$forge->setBody($body); // The post DATA

$data = $forge->getJson();
```

It return : 

```
Variable #1:
  (Array, 4 elements) ↵
     debug (String): "" (0 characters)
     string (String): "Internal Server Error (ut)" (26 characters)
     reason (String): "" (0 characters)
     code (String): "500" (3 characters)
```

What's the problem ? How i can relist an auction please ?

**Comment by ebess** [comment]
You need to check the webapp request first. You will see the request body is an encoded json.
So you need to add the second paramter setBody($body, true). I will force the body to be converted to a json-string. Otherwise it will be a query-string (x=1&y=2...).
