### ISSUE TITLE
Keep the login

### ISSUE THREAD

**Issue by jhuriez** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#8]
On all request, the class re-login again on the FUT15 App. How it's possible to kept the login session for no re-login again ?

**Comment by ebess** [comment]
You need to store the exported data somewhere and the cookiesjar as well.

**Comment by jhuriez** [comment]
Thanks it's work. The class throw an exception if the login session is expired or doesn't works ?

**Comment by ebess** [comment]
No, the api anwers with some kind of an answer that tells you the session expired.
You have to assign a subscriber to the guzzle client which will react on expiring answer.
Just provoke a session expires message yourself and take a look at guzzle docs.

**Comment by mikebyte00** [comment]
Can either of you two please go into more detail about preserving the cookiejar for different .php files and functions to use.

I can get the cookiejar but i'm not sure where to store it. What temporary solutions are you using? e.g. cache or file cookie?
