### ISSUE TITLE
Login verification

### ISSUE THREAD

**Issue by LUFCMOT** [ebess/Fifa-15-Ultimate-Team-WebApp-Api#9]
How can i add the function for login verification? I am unsure how to find the URL to post my data too.

```
     $request = $this->_client->post($url, array(), array(
                    "twoFactorCode" => Code here,
                    "_trustThisDevice" => "on",
                    "trustThisDevice" => "on",
                    "_eventId" => "submit"               
            ));
            $response = $request->send();
```

This is what I have added but I cannot seem to get the correct request url

**Comment by Unsworth94** [comment]
My login() method now looks like this

``` php
private function login($url, $try = 1)
    {
        $forge = $this->getForge($url, 'post');
        $data = $forge
            ->addHeader('Content-Type', 'application/x-www-form-urlencoded')
            ->removeEndpointHeaders()
            ->setBody(array(
                "email" => $this->email,
                "password" => $this->password,
                "_rememberMe" => "on",
                "rememberMe" => "on",
                "_eventId" => "submit",
                "facebookAuth" => ""
            ))
            ->sendRequest();
        if($try == 0 ) {
            $postURL = $data['response']->getEffectiveUrl(); //get location url from above post
            $forge = $this->getForge($postURL, 'get');
            $forge->removeEndpointHeaders()->sendRequest();
            sleep(3); //pause and allow time for EA to email code
            //do a request here to get code from inbox of email

                       //post code to url
            $forge = $this->getForge($postURL, 'post');
            $body = $forge
            ->addHeader('Content-Type', 'application/x-www-form-urlencoded')
            ->removeEndpointHeaders()
            ->setBody(array(
                "twoFactorCode" => $code['code'], //code here
                "_trustThisDevice" => "on",
                "trustThisDevice" => "on",
                "_eventId" => "submit"
            ))
            ->sendRequest();
                        //follow location of the rest of the urls
            $forge = $this->getForge($body['response']->getEffectiveUrl(), 'get');
            $data = $forge->removeEndpointHeaders()->sendRequest();
            $forge = $this->getForge($body['response']->getEffectiveUrl(), 'get');
            $data = $forge->removeEndpointHeaders()->sendRequest();
            $forge = $this->getForge($body['response']->getEffectiveUrl(), 'get');
            $data = $forge->removeEndpointHeaders()->sendRequest();
            $forge = $this->getForge($body['response']->getEffectiveUrl(), 'get');
            $data = $forge->removeEndpointHeaders()->sendRequest();
            return 0;
        }

        return $this;
    }
```

and my connect() method looks like this:

``` php
 public function connect()
    {

        $url = $this->getMainPage();

        $this->login($url, 0);
        $url = $this->getMainPage();
        $this
            ->login($url, 1)
            ->getNucleusId()
            ->getShards()
            ->getUserAccounts()
            ->getSessionId()
            ->getPhishing()
            ->validate();

        return $this;
    }
```

I will be cleaning up this code in the morning so I shall repost the code then.

**Comment by LUFCMOT** [comment]
You are a legend, I just couldn't get my head around it

**Comment by scronberg** [comment]
Anyone has any idea on how to get it to work on https://github.com/curt2008/FIFA15-Unofficial-API

I can't install your because I can't change my php version that's required for the composer

**Comment by ebess** [comment]
Sorry, you got to ask the owner of the other repository how to handle it.

@Unsworth94
Feel free to make a pull request, i would merge it to master.

**Comment by Unsworth94** [comment]
@ebess I actually couldn't get a clean way of writing out it all using forge as im pretty foreign to it. I can send you my login class which is also using guzzle and you can implement it into your system. Just let me know.

**Comment by gurstacey** [comment]
@ebess thanks for this works really well for me. I hear there is a way using cookies that you can login so that you do not have to repeatedly request the email code. It has been discussed here https://github.com/trydis/FIFA-Ultimate-Team-2015-Toolkit/issues/93 I havent had chance to try it out yet. Do you have any plans to update the WebApp/Mobile classes to support this?

**Comment by ebess** [comment]
@Unsworth94 
Can you open a new issue and paste the http request with all headers needed + body? Obv you should replace your sensible data. Afterwards I will send you the forge code snippet you can use.

@gurstacey 
I mentioned in some other issues: I do not work actively on the fut api this session. i may start developing it in late spring - unfortunately right now im too busy working on other stuff. If you have further questions or requests, just create new issue please!

best regards!

**Comment by mikebyte00** [comment]
Firstly, thankyou Edward for your api code. I don't play Fifa myself but am an aspiring web developer so have made it my mission to develop an application to interact with Fifa's Ultimate Team.

I've manage to implement your code with little error however the two-step verification is a problem.
The other API on Github has a workaround by using Origin's 'Backup Codes' from the security part of your account. I spoke to him myself. Haven't implemented it yet, but hope it helps some how.

**Comment by rorentz** [comment]
Anyone has the working solution?
